name: Deploy Dynamic Next.js to cPanel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install and Build
      env:
        NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      run: |
        npm ci --force
        npm run build -- --no-lint
        npm prune --production --force

    - name: Prepare Deployment
      run: |
        mkdir -p deployment
        cp -r .next/ deployment/
        cp -r public/ deployment/
        cp -r node_modules/ deployment/
        cp package.json deployment/
        cp package-lock.json deployment/
        [ -f "next.config.mjs" ] && cp next.config.mjs deployment/

        echo 'module.exports = {
          apps: [{
            name: "next-app",
            script: "node_modules/next/dist/bin/next",
            args: "start",
            cwd: "/home/tandtrav/tandtravel.md/tandtravel",
            instances: "max",
            exec_mode: "cluster",
            env: {
              NODE_ENV: "production",
              PORT: 3000,
              NEXT_PUBLIC_BASE_URL: "${NEXT_PUBLIC_BASE_URL}",
              MONGODB_URI: "${MONGODB_URI}",
              AUTH_TRUST_HOST: "${AUTH_TRUST_HOST}",
              AUTH_SECRET: "${AUTH_SECRET}",
              NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}",
              NEXT_PUBLIC_FIREBASE_API_KEY: "${NEXT_PUBLIC_FIREBASE_API_KEY}",
              NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}",
              NEXT_PUBLIC_FIREBASE_PROJECT_ID: "${NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
            }
          }]
        }' > deployment/ecosystem.config.js

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deployment/
        server-dir: ./tandtravel.md/tandtravel/
        dangerous-clean-slate: false
        protocol: ftp
