name: Deploy Dynamic Next.js to cPanel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install and build with production dependencies
    - name: Install and Build
      run: |
        npm ci --force
        npm run build -- --no-lint
        npm prune --production --force

    # Prepare deployment package
    - name: Prepare Deployment
      run: |
        mkdir -p deployment
        # Essential files for dynamic site
        cp -r .next/ deployment/
        cp -r public/ deployment/
        cp -r node_modules/ deployment/  # Critical for dynamic sites
        cp package.json deployment/
        cp package-lock.json deployment/
        cp next.config.js deployment/
        
        # Create PM2 ecosystem file
        echo 'module.exports = {
          apps: [{
            name: "next-app",
            script: "node_modules/next/dist/bin/next",
            args: "start",
            cwd: "/home/tandtrav/public_html",
            instances: "max",
            exec_mode: "cluster",
            env: {
              NODE_ENV: "production",
              PORT: 3000
            }
          }]
        }' > deployment/ecosystem.config.js

    # FTP Deploy
    - name: FTP Deploy Dynamic App
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deployment/
        server-dir: /home/tandtrav/public_html/
        dangerous-clean-slate: false
        server-dotfiles: true
